language:
  python
python:
  - 3.6
install:
  - pip install -e .
script:
  nosetests --verbose
notifications:
  email:
    - mfrager@gmail.com
after_success:
  - pip install coveralls
  - coverage run --source=triplesec setup.py -q nosetests
  - coveralls
