language:
  python
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
script:
  nosetests --verbose
notifications:
  email:
    - max@keybase.io
after_success:
  - pip install coveralls
  - coverage run --source=triplesec setup.py -q nosetests
  - coveralls
